# -*- coding: utf-8 -*-
"""Cuaderno-MCON-ModelosAtmosféricos-Clase-Original.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUlb7yFv60kD2_dX4KIwsKYlyRjtxFrr

# Mecánica de Medios Continuos
## Por Jorge I. Zuluaga
### Cuadernos de exploración numérica

## Modelos Atmosféricos

Propiedades de la atmósfera de la Tierra:
"""

atm=101.325e3 # Pa
po=1*atm
ρo=1.225 # kg/m^3
go=9.80665 # m/s^2
ho=po/(ρo*go)
R = 6378000 # m
omega = 7.29e-15 #rev/s
print(f"Escala vertical de la atmósfera barotrópica: {ho/1e3} km")

"""### Modelo incompresible"""

import numpy as np
hmax=20e3 # m
zs=np.linspace(0,hmax,100) # m
ps_inc=po-ρo*go*zs
ρs_inc=ρo*np.ones_like(ps_inc)

"""Gráfico normal:"""

import matplotlib.pyplot as plt
fig,ax=plt.subplots(figsize=(6,3))
ax.plot(zs/1e3,ps_inc/atm,'b-')
axd=ax.twinx()
axd.plot(zs/1e3,ρs_inc,'b:')

#Decoración
ax.set_xlabel("z [km]")
ax.set_ylabel("p [atm]")
axd.set_ylabel("ρ [kg/m$^3$]")
ax.margins(0,0)
ax.set_ylim(0,1)
fig.tight_layout()

"""Gráfico como se acostumbra hacerlo en ciencias atmosféricas:"""

import matplotlib.pyplot as plt
fig,ax=plt.subplots(figsize=(6,3))

#Presión
ax.plot(ps_inc/atm,zs/1e3,'b-')
#Densidad
axd=ax.twiny()
axd.plot(ρs_inc,zs/1e3,'b:')

#Decoración
ax.set_xlabel("p [atm]")
ax.set_ylabel("z [km]")
axd.set_xlabel("ρ [kg/m$^3$]")
ax.margins(0,0)
ax.set_ylim(0,hmax/1e3)
ax.set_xlim(0,1)
fig.tight_layout()

"""### Modelo isotérmico"""

ps_iso=po*np.exp(-zs/ho)
ρs_iso=ρo*np.exp(-zs/ho)

fig,ax=plt.subplots(figsize=(6,6))

#Presión
ax.plot(ps_inc/atm,zs/1e3,'b-',label='Incompresible')
ax.plot(ps_iso/atm,zs/1e3,'r-',label='Isotérmica')

#Densidad
axd=ax.twiny()
axd.plot(ρs_inc,zs/1e3,'b:')
axd.plot(ρs_iso,zs/1e3,'r:')

#Decoración
ax.legend()
ax.set_xlabel("p [atm]")
ax.set_ylabel("z [km]")
axd.set_xlabel("ρ [kg/m$^3$]")
ax.margins(0,0)
ax.set_ylim(0,hmax/1e3)
ax.set_xlim(0,1)
fig.tight_layout()

"""### Atmósfera estándar

Una atmósfera estándar usada en la industria aeronáutica es la definida por International Civil Aviation Organization (ICAO). Este modelo puede accederse con este paquete: https://pypi.org/project/ambiance/
"""

!python -m pip install ambiance

from ambiance import Atmosphere

ps_grav=po*np.exp(-zs/ho*1/(1+zs/R))
ps_rot=po*np.exp(-zs/ho*(1/(1+zs/R)-omega*R/go*(1+zs/R)))

ρs_grav=ρo*np.exp(-zs/ho*1/(1+zs/R))
ρs_rot=ρo*np.exp(-zs/ho*(1/(1+zs/R)-omega*R/go*(1+zs/R)))

fig,ax=plt.subplots(figsize=(6,6))

#Presión
ax.plot(ps_iso/atm,zs/1e3,'b-',label='Isotérmica')
ax.plot(ps_grav/atm,zs/1e3,'r-',label='Gravedad variable')
ax.plot(ps_rot/atm,zs/1e3,'k-',label='Rotación')

#Densidad
axd=ax.twiny()
axd.plot(ρs_iso,zs/1e3,'b:')
axd.plot(ρs_grav,zs/1e3,'r:')
axd.plot(ρs_rot,zs/1e3,'k:')

#Decoración
ax.legend()
ax.set_xlabel("p [atm]")
ax.set_ylabel("z [km]")
axd.set_xlabel("ρ [kg/m$^3$]")
ax.margins(0,0)
ax.set_ylim(0,hmax/1e3)
ax.set_xlim(0,1)
fig.tight_layout()

atmosphere=Atmosphere(zs)
ps_icao=atmosphere.pressure
ρs_icao=atmosphere.density

fig,ax=plt.subplots(figsize=(6,6))

#Presión
ax.plot(ps_inc/atm,zs/1e3,'b-',label='Incompresible')
ax.plot(ps_iso/atm,zs/1e3,'r-',label='Isotérmica')
ax.plot(ps_icao/atm,zs/1e3,'k-',label='Standard ICAO')

#Densidad
axd=ax.twiny()
axd.plot(ρs_inc,zs/1e3,'b:')
axd.plot(ρs_iso,zs/1e3,'r:')
axd.plot(ρs_icao,zs/1e3,'k:')

#Decoración
ax.legend()
ax.set_xlabel("p [atm]")
ax.set_ylabel("z [km]")
axd.set_xlabel("ρ [kg/m$^3$]")
ax.margins(0,0)
ax.set_ylim(0,hmax/1e3)
ax.set_xlim(0,1)
fig.tight_layout()

"""La temperatura:"""

Ts_icao=atmosphere.temperature_in_celsius
fig,ax=plt.subplots(figsize=(6,6))
ax.plot(Ts_icao,zs/1e3,'k--',label='Standard ICAO')

#Decoración
ax.legend()
ax.set_xlabel("T [C]")
ax.set_ylabel("z [km]")
fig.tight_layout()

"""### Modelo homentrópico

Propiedades asumidas para la atmósfera:
"""

γ=7/5
R=8.31446261815324
To=15+273.15 #K
Mmol=29e-3 # kg/mol
cP=R*γ/(γ-1)/Mmol
h2=γ/(γ-1)*ho
dTdz=go/cP
print(f"Calor específico a presión constante: {cP} J/K/kg")
print(f"Temperature lapse rate: {dTdz*1e3} K/km")
print(f"Scale height de Temperatura: {h2/1e3} km")

"""Solución a la ecuación de equilibrio hidrostático:"""

Ts_hom=To*(1-zs/h2)
ρs_hom=ρo*(1-zs/h2)**(1/(γ-1))
ps_hom=po*(1-zs/h2)**(γ/(γ-1))

Ts_icao=atmosphere.temperature_in_celsius
fig,ax=plt.subplots(figsize=(6,6))
ax.plot(Ts_icao,zs/1e3,'k--',label='Standard ICAO')
ax.plot(Ts_hom-273.2,zs/1e3,'k--',label='Homentrópico')

#Decoración
ax.legend()
ax.set_xlabel("T [C]")
ax.set_ylabel("z [km]")
fig.tight_layout()

fig,ax=plt.subplots(figsize=(6,6))

#Presión
ax.plot(ps_inc/atm,zs/1e3,'b-',label='Incompresible')
ax.plot(ps_iso/atm,zs/1e3,'r-',label='Isotérmica')
ax.plot(ps_icao/atm,zs/1e3,'k-',label='Standard ICAO')
ax.plot(ps_hom/atm,zs/1e3,'c-',label='Homentrópica')

#Densidad
axd=ax.twiny()
axd.plot(ρs_inc,zs/1e3,'b:')
axd.plot(ρs_iso,zs/1e3,'r:')
axd.plot(ρs_icao,zs/1e3,'k:')
axd.plot(ρs_hom,zs/1e3,'c:')

#Decoración
ax.legend()
ax.set_xlabel("p [atm]")
ax.set_ylabel("z [km]")
axd.set_xlabel("ρ [kg/m$^3$]")
ax.margins(0,0)
ax.set_ylim(0,hmax/1e3)
ax.set_xlim(0,1)
fig.tight_layout()

"""## Atmósfera empírica"""

!pip install -q nrlmsise00
!pip install -qU 'nrlmsise00[dataset]'
!pip install -q spaceweather

from nrlmsise00.dataset import msise_4d
from datetime import datetime
import spaceweather as sw
#NRLMSISE-00 usa datos del clima espacial.  Esos datos tienen que actualizarse
sw.update_data()

ds = msise_4d(datetime(2023,8,29,12,0,0),zs/1e3,[45],[0])

ds

"""**NOTA**: la rutina `msise_4d` usa `xarray` un tipo de arreglo multidimensional muy poderoso y versatil.  Para una guía sobre el manejo de este tipo de arreglos ver http://xarray.pydata.org/en/stable/index.html.

Podemos obtener los perfiles de densidad y de temperatura usando:
"""

np.array(ds['O2']).shape

ρs_emp=np.array(ds["rho"]).flatten()
Ts_emp=np.array(ds["Talt"]).flatten()

"""Ahora podemos comparar la atmósfera empírica con la atmósfera homentrópica:"""

fig,ax=plt.subplots(figsize=(6,6))

#Presión
ax.plot(Ts_hom-273.15,zs/1e3,'c-')
ax.plot(Ts_emp-273.15,zs/1e3,'k-')

#Densidad
axd=ax.twiny()
axd.plot(ρs_hom,zs/1e3,'c:',label='Homéntrópica')
axd.plot(ρs_emp*1e3,zs/1e3,'k:',label='Empírica')

#Decoración
axd.legend()
ax.set_xlabel("T [C]")
ax.set_ylabel("z [km]")
axd.set_xlabel("ρ [kg/m$^3$]")
ax.margins(0,0)
#ax.set_ylim(0,hmax/1e3)
fig.tight_layout()

zs = np.linspace(0,80e3,100)
ds = msise_4d(datetime(2024,3,5,17,0,0),zs/1e3,[0],[0])
Ts_emp=np.array(ds["Talt"]).flatten()

fig,ax=plt.subplots(figsize=(6,6))

#Presión
ax.plot(Ts_emp-273.15,zs/1e3,'k-')

#Decoración
axd.legend()
ax.set_xlabel("T [C]")
ax.set_ylabel("z [km]")
ax.margins(0,0)
fig.tight_layout()

!pip install -Uq mendeleev

from mendeleev import element

O = element('Oxygen')
N = element('Nitrogen')
Ar = element('Argon')
H = element(1)

O.atomic_weight

species = [
    dict(name='N2',Mmol=2*element('Nitrogen').atomic_weight),
    dict(name='O2',Mmol=2*element('Oxygen').atomic_weight),
    dict(name='Ar',Mmol=1*element('Argon').atomic_weight),
    dict(name='N',Mmol=1*element('Nitrogen').atomic_weight),
    dict(name='O',Mmol=1*element('Oxygen').atomic_weight),
    dict(name='H',Mmol=1*element('Hydrogen').atomic_weight),
]
ns = np.zeros(len(species))
ms = np.zeros(len(species))
for i,specie in enumerate(species):
  ns[i] = np.array(ds[specie['name']]).flatten()[-1]
  ms[i] = specie['Mmol']*ns[i]
n = ns.sum()
Mmol = ms.sum()/n
Mmol

"""Asumimos gas ideal:

$$
\frac{p}{\rho} = \frac{RT}{M_\text{mol}}
$$
"""

from scipy import constants as c

c.R

ds['rho']

p = c.R*np.array(ds['rho']).flatten()[0]*1e3*np.array(ds['Talt']).flatten()[0]/(Mmol*1e-3)
p

